language: ruby
rvm:
- 2.7.2
cache:
- bundler
services:
- postgresql
script:
- bundle install --jobs=3 --retry=3
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: 12M6mGXteoACqxMwAMRKUd+af9M+oaAn2FGnEN2Ra9ODZbbQyjqXdQC5zIQYxCUPYPmCs0rRh87QLNI0d5paWJpSZcdmohNqlmeSfqm+wlYJonqtnCBj1ypJ4v22EFUDLdspzaSO7flYpOZMhBd1mZ6nJ0SWKAMJcRCsIZ0qNhCfkEu2+3c7tGVNzilh5HT14vuegTZg9G8RUvBv9vU6TjROp+YhpJaOBnF+jh8lHW7N7G9XzvWA2Wlc8CcxAZlK+zRtFrq3VlL5+5+2f5co5u3e5tYGO3XKW5x0YAQ3BJ8BvJpcjYt3IlQ6vpq7NURLikeinslVvax/sdGGSyi+ksGpBSikyYtlv4YpY4IgUxRoARqqattMvghyLOTVjBTWXwniTWEbwgIHvjIVfy44jYV1f1zrnnuMWBNd+jmUK36KVGiX0uKZDw4CMnT6bdpKYk2GbxoHNrMFKcZAd2EAIErVqFRafYrYxbc/K+mfy5iwKlnKmkc6fGuXVdrFJYGmQvAVw5kr5CV52TvsTFgvvMxlQf4EJjwZeG2nyZrOAg7RxiWme9VYbx8NVXYdgeT262EEVGsFzUuWHAvTm4tnS+o+YHKktpwwdQtJqk8/Sszh/WP3qVmMhQ4UWEIwMGCWMSo8PfklPkfDTzl+dtLxcFEo9m97+OqutgUW+M7Bvmc=
  app: calm-escarpment-13056
  on:
    repo: sejinkim1904/robot_sports_league_api
